# /// script
# requires-python = ">=3.14"
# dependencies = [
#     "marimo>=0.24.2",
#     "psycopg==3.3.6",
# ]
# ///

import marimo

__generated_with = "0.24.2"
app = marimo.App(width="medium")


@app.cell
def _():
    import os
    import re

    import marimo as mo
    import psycopg
    from psycopg import sql

    return mo, os, psycopg, re, sql


@app.cell
def _(os):
    # Parâmetros de servidor (podem ser definidos por variáveis de ambiente);
    # o utilizador e a password vêm do formulário de autenticação abaixo.
    DB_NAME = "contabilidade"
    DB_HOST = os.getenv("PGHOST", "localhost")
    DB_PORT = int(os.getenv("PGPORT", "5432"))
    return DB_HOST, DB_NAME, DB_PORT


@app.cell
def _(mo):
    # 1) Autenticação
    login_form = (
        mo.md(
            """
            # Movimentos

            ## Autenticação

            {utilizador}

            {password}
            """
        )
        .batch(
            utilizador=mo.ui.text(value="", label="Utilizador"),
            password=mo.ui.text(value="", label="Password", kind="password"),
        )
        .form(submit_button_label="Entrar")
    )
    login_form
    return (login_form,)


@app.cell
def _(DB_HOST, DB_PORT, login_form, mo, psycopg):
    mo.stop(
        login_form.value is None,
        mo.md("Introduza as suas credenciais e carregue em **Entrar**."),
    )

    _utilizador = login_form.value["utilizador"].strip()
    _password = login_form.value["password"]

    try:
        with psycopg.connect(
            host=DB_HOST,
            port=DB_PORT,
            user=_utilizador,
            password=_password,
            dbname="postgres",
            connect_timeout=5,
        ):
            pass
    except psycopg.OperationalError as _erro:
        mo.stop(True, mo.md(f"**Autenticação falhada:** {_erro}"))

    params = dict(host=DB_HOST, port=DB_PORT, user=_utilizador, password=_password)
    utilizador = _utilizador
    autenticado = True
    mo.md(f"Sessão iniciada como **{utilizador}**. ✅")
    return autenticado, params, utilizador


@app.cell
def _(autenticado, mo):
    # 2) Comando para fechar a aplicação
    _ = autenticado
    fechar_botao = mo.ui.run_button(label="⏻ Fechar aplicação")
    fechar_botao
    return (fechar_botao,)


@app.cell
def _(fechar_botao, mo, os):
    if fechar_botao.value:
        mo.md("A fechar a aplicação. Pode fechar esta janela do browser.")
        os._exit(0)
    return


@app.cell
def _(DB_NAME, params, psycopg):
    # 3) Preparar a base de dados (idempotente; requer privilégios de administrador
    # na primeira execução, tipicamente ligado como "postgres")
    avisos_setup = []

    try:
        with psycopg.connect(**params, dbname="postgres", autocommit=True) as conn_admin:
            _existe = conn_admin.execute(
                "SELECT 1 FROM pg_database WHERE datname = %s", (DB_NAME,)
            ).fetchone()
            if not _existe:
                conn_admin.execute(f'CREATE DATABASE "{DB_NAME}"')
    except psycopg.errors.InsufficientPrivilege:
        avisos_setup.append("Sem privilégios para criar a base de dados.")

    try:
        with psycopg.connect(**params, dbname=DB_NAME) as conn_ddl:
            conn_ddl.execute(
                """
                CREATE TABLE IF NOT EXISTS movimentos (
                    id          BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
                    cliente     TEXT           NOT NULL,
                    descricao   TEXT,
                    credito     NUMERIC(14,2)  NOT NULL DEFAULT 0 CHECK (credito >= 0),
                    debito      NUMERIC(14,2)  NOT NULL DEFAULT 0 CHECK (debito  >= 0),
                    "data&hora" TIMESTAMPTZ    NOT NULL DEFAULT now(),
                    saldo       NUMERIC(14,2)  NOT NULL DEFAULT 0,
                    "correção"  BOOLEAN        NOT NULL DEFAULT FALSE
                )
                """
            )
            # Garante a coluna "id" e "correção" também em bases de dados criadas
            # antes destas alterações
            conn_ddl.execute(
                """
                ALTER TABLE movimentos
                    ADD COLUMN IF NOT EXISTS id BIGINT GENERATED BY DEFAULT AS IDENTITY
                """
            )
            conn_ddl.execute(
                """
                ALTER TABLE movimentos
                    ADD COLUMN IF NOT EXISTS "correção" BOOLEAN NOT NULL DEFAULT FALSE
                """
            )
            # Função e trigger: calculam automaticamente o saldo acumulado
            # (credito - debito desta linha e de todas as anteriores) em cada inserção
            conn_ddl.execute(
                """
                CREATE OR REPLACE FUNCTION calcular_saldo() RETURNS TRIGGER AS $$
                DECLARE
                    saldo_anterior NUMERIC(14,2);
                BEGIN
                    SELECT saldo INTO saldo_anterior
                    FROM movimentos
                    ORDER BY "data&hora" DESC, ctid DESC
                    LIMIT 1;

                    NEW.saldo := COALESCE(saldo_anterior, 0) + NEW.credito - NEW.debito;
                    RETURN NEW;
                END;
                $$ LANGUAGE plpgsql
                """
            )
            conn_ddl.execute("DROP TRIGGER IF EXISTS trg_calcular_saldo ON movimentos")
            conn_ddl.execute(
                """
                CREATE TRIGGER trg_calcular_saldo
                    BEFORE INSERT ON movimentos
                    FOR EACH ROW
                    EXECUTE FUNCTION calcular_saldo()
                """
            )
            # Privilégios: só o "postgres" (dono da tabela) pode alterar ou apagar
            # linhas. Todos os restantes utilizadores só podem consultar e
            # acrescentar (append) novos registos — nunca UPDATE nem DELETE.
            conn_ddl.execute("REVOKE ALL ON movimentos FROM PUBLIC")
            conn_ddl.execute("GRANT SELECT, INSERT ON movimentos TO PUBLIC")
    except psycopg.errors.InsufficientPrivilege:
        avisos_setup.append(
            "Sem privilégios para criar/alterar a tabela ou os seus privilégios de acesso."
        )

    bd_pronta = True
    return avisos_setup, bd_pronta


@app.cell
def _(avisos_setup, mo):
    aviso_md = (
        mo.md("\n\n".join(f"⚠️ {aviso}" for aviso in avisos_setup))
        if avisos_setup
        else mo.md("")
    )
    aviso_md
    return (aviso_md,)


@app.cell
def _(bd_pronta, mo):
    # 4) Comando para criar um novo registo
    _ = bd_pronta
    form = (
        mo.md(
            """
            ## Nova entrada

            {cliente}

            {descricao}

            {credito}

            {debito}

            {correcao}
            """
        )
        .batch(
            cliente=mo.ui.text(value="", label="Cliente"),
            descricao=mo.ui.text(value="", label="Descrição"),
            credito=mo.ui.number(
                start=0, stop=10**12, step=0.01, value=0, label="Crédito (€)"
            ),
            debito=mo.ui.number(
                start=0, stop=10**12, step=0.01, value=0, label="Débito (€)"
            ),
            correcao=mo.ui.checkbox(
                value=False,
                label="Este registo corrige valores de registos anteriores",
            ),
        )
        .form(submit_button_label="Inserir")
    )
    form
    return (form,)


@app.cell
def _(DB_NAME, bd_pronta, form, mo, params, psycopg):
    assert bd_pronta
    inserido = form.value is not None
    if inserido:
        with psycopg.connect(**params, dbname=DB_NAME) as conn_ins:
            conn_ins.execute(
                'INSERT INTO movimentos (cliente, descricao, credito, debito, "correção") '
                "VALUES (%s, %s, %s, %s, %s)",
                (
                    form.value["cliente"],
                    form.value["descricao"],
                    form.value["credito"],
                    form.value["debito"],
                    form.value["correcao"],
                ),
            )
        mensagem = mo.md(f"Entrada inserida para **{form.value['cliente']}**.")
    else:
        mensagem = mo.md("_Preencha o formulário e carregue em **Inserir**._")
    mensagem
    return (inserido,)


@app.cell
def _(mo):
    # 5) Comando para selecionar registos, incluindo limites numéricos
    # (mínimo/máximo) opcionais para crédito, débito e saldo. Usam campos de
    # texto — não campos numéricos — para ficarem mesmo "não preenchidos" por
    # omissão, em vez de mostrarem um valor por defeito.
    filtro_form = (
        mo.md(
            """
            ## Selecionar registos

            {cliente}

            {apenas_correcoes}

            **Crédito (€) entre:** {credito_min} e {credito_max}

            **Débito (€) entre:** {debito_min} e {debito_max}

            **Saldo (€) entre:** {saldo_min} e {saldo_max}
            """
        )
        .batch(
            cliente=mo.ui.text(value="", label="Cliente (deixe vazio para todos)"),
            apenas_correcoes=mo.ui.checkbox(
                value=False, label="Mostrar apenas correções"
            ),
            credito_min=mo.ui.text(value="", label="mín."),
            credito_max=mo.ui.text(value="", label="máx."),
            debito_min=mo.ui.text(value="", label="mín."),
            debito_max=mo.ui.text(value="", label="máx."),
            saldo_min=mo.ui.text(value="", label="mín."),
            saldo_max=mo.ui.text(value="", label="máx."),
        )
        .form(submit_button_label="Selecionar")
    )
    filtro_form
    return (filtro_form,)


@app.cell
def _(DB_NAME, bd_pronta, filtro_form, inserido, mo, params, psycopg):
    # 6) Apresentar a seleção (as linhas podem ser marcadas na tabela para,
    # se o utilizador for "postgres", serem purgadas — ver secção seguinte)
    _ = (bd_pronta, inserido)
    mo.stop(
        filtro_form.value is None,
        mo.md("_Preencha os filtros e carregue em **Selecionar**._"),
    )

    def _numero_ou_none(texto):
        texto = (texto or "").strip().replace(",", ".")
        return float(texto) if texto else None

    _valores = filtro_form.value
    _cliente = _valores["cliente"].strip()
    _so_correcoes = _valores["apenas_correcoes"]

    _condicoes = []
    _parametros = []

    if _cliente:
        _condicoes.append("cliente ILIKE %s")
        _parametros.append(f"%{_cliente}%")
    if _so_correcoes:
        _condicoes.append('"correção" = TRUE')

    _limites = (
        ("credito", "credito_min", "credito_max"),
        ("debito", "debito_min", "debito_max"),
        ("saldo", "saldo_min", "saldo_max"),
    )
    try:
        for _coluna, _chave_min, _chave_max in _limites:
            _minimo = _numero_ou_none(_valores[_chave_min])
            _maximo = _numero_ou_none(_valores[_chave_max])
            if _minimo is not None:
                _condicoes.append(f"{_coluna} >= %s")
                _parametros.append(_minimo)
            if _maximo is not None:
                _condicoes.append(f"{_coluna} <= %s")
                _parametros.append(_maximo)
    except ValueError:
        mo.stop(
            True,
            mo.md(
                "**Limite numérico inválido.** Introduza apenas números "
                "(ex.: `100` ou `100.50`) nos campos de crédito, débito e saldo."
            ),
        )

    _sql = (
        'SELECT id, cliente, descricao, credito, debito, "data&hora", saldo, "correção" '
        "FROM movimentos"
    )
    if _condicoes:
        _sql += " WHERE " + " AND ".join(_condicoes)
    _sql += ' ORDER BY "data&hora"'

    with psycopg.connect(**params, dbname=DB_NAME) as conn_sel:
        _linhas = conn_sel.execute(_sql, _parametros).fetchall()

    resultado_tabela = mo.ui.table(
        [
            {
                "id": rid,
                "cliente": c,
                "descricao": d,
                "credito (€)": float(cr),
                "debito (€)": float(db),
                "data & hora": dh,
                "saldo (€)": float(sa),
                "correção": corr,
            }
            for rid, c, d, cr, db, dh, sa, corr in _linhas
        ],
        label=f"Movimentos ({len(_linhas)} registo(s)) — selecione linhas para purgar",
        selection="multi",
    )
    resultado_tabela
    return (resultado_tabela,)


@app.cell
def _(mo, resultado_tabela, utilizador):
    # 7) Purgar registos selecionados — só disponível para o utilizador "postgres".
    # O painel de confirmação aparece diretamente assim que houver linhas
    # marcadas na tabela acima (sem um botão intermédio de "pedido de purga",
    # que se mostrou pouco fiável).
    _selecionados = resultado_tabela.value or []

    if utilizador != "postgres":
        painel_purga = mo.md("_Só o utilizador **postgres** pode purgar registos._")
        confirmar_purga_botao = None
        cancelar_purga_botao = None
    elif not _selecionados:
        painel_purga = mo.md(
            "_Selecione uma ou mais linhas na tabela acima para poder purgá-las._"
        )
        confirmar_purga_botao = None
        cancelar_purga_botao = None
    else:
        confirmar_purga_botao = mo.ui.run_button(label="✅ Confirmar purga definitiva")
        cancelar_purga_botao = mo.ui.run_button(label="Cancelar")
        painel_purga = mo.vstack(
            [
                mo.md(
                    f"⚠️ **{len(_selecionados)}** registo(s) selecionado(s) para "
                    "purgar. Esta ação é irreversível."
                ),
                mo.hstack([confirmar_purga_botao, cancelar_purga_botao]),
            ]
        )

    painel_purga
    return cancelar_purga_botao, confirmar_purga_botao


@app.cell
def _(
    DB_NAME,
    cancelar_purga_botao,
    confirmar_purga_botao,
    mo,
    params,
    psycopg,
    resultado_tabela,
    utilizador,
):
    # 8) Executa (ou cancela) a purga depois da confirmação explícita acima
    if confirmar_purga_botao is not None and confirmar_purga_botao.value:
        _ids = [linha["id"] for linha in resultado_tabela.value]
        with psycopg.connect(**params, dbname=DB_NAME) as conn_del:
            conn_del.execute("DELETE FROM movimentos WHERE id = ANY(%s)", (_ids,))
        mensagem_purga = mo.md(f"{len(_ids)} registo(s) purgado(s) por **{utilizador}**.")
    elif cancelar_purga_botao is not None and cancelar_purga_botao.value:
        mensagem_purga = mo.md(
            "Purga cancelada — nada foi apagado. Desmarque as linhas na tabela "
            "acima, se quiser limpar a seleção."
        )
    else:
        mensagem_purga = mo.md("")
    mensagem_purga
    return


@app.cell
def _(mo, utilizador):
    # 9) Criar novo utilizador — só disponível para o utilizador "postgres".
    # O novo utilizador não recebe nenhum privilégio explícito: fica apenas com
    # o que já está concedido a PUBLIC (hoje: SELECT + INSERT em "movimentos").
    if utilizador == "postgres":
        criar_utilizador_form = (
            mo.md(
                """
                ## Criar novo utilizador

                Fica com os mesmos privilégios de PUBLIC nesta base de dados
                (atualmente: consultar e acrescentar registos em `movimentos`,
                sem poder alterar nem apagar).

                {nome}

                {password}

                {confirmar_password}
                """
            )
            .batch(
                nome=mo.ui.text(value="", label="Nome de utilizador"),
                password=mo.ui.text(value="", label="Password", kind="password"),
                confirmar_password=mo.ui.text(
                    value="", label="Confirmar password", kind="password"
                ),
            )
            .form(submit_button_label="Criar utilizador")
        )
    else:
        criar_utilizador_form = None

    # Expressão final incondicional (ver nota na secção de purga acima).
    criar_utilizador_form if criar_utilizador_form is not None else mo.md(
        "_Só o utilizador **postgres** pode criar novos utilizadores._"
    )
    return (criar_utilizador_form,)


@app.cell
def _(criar_utilizador_form, mo, params, psycopg, re, sql):
    mo.stop(criar_utilizador_form is None or criar_utilizador_form.value is None)

    _nome = criar_utilizador_form.value["nome"].strip()
    _password = criar_utilizador_form.value["password"]
    _confirmar = criar_utilizador_form.value["confirmar_password"]

    if not re.fullmatch(r"[A-Za-z_][A-Za-z0-9_]*", _nome):
        mo.stop(
            True,
            mo.md(
                "**Nome de utilizador inválido.** Use apenas letras, números e "
                "underscore, começando por uma letra ou underscore."
            ),
        )

    if not _password or _password != _confirmar:
        mo.stop(True, mo.md("**As passwords não coincidem (ou estão vazias).**"))

    try:
        with psycopg.connect(**params, dbname="postgres", autocommit=True) as conn_role:
            conn_role.execute(
                sql.SQL("CREATE ROLE {} WITH LOGIN PASSWORD %s").format(
                    sql.Identifier(_nome)
                ),
                (_password,),
            )
        mensagem_utilizador = mo.md(
            f"Utilizador **{_nome}** criado com sucesso, com os privilégios de "
            "PUBLIC (herdados automaticamente)."
        )
    except psycopg.errors.DuplicateObject:
        mensagem_utilizador = mo.md(f"⚠️ Já existe um utilizador chamado **{_nome}**.")
    mensagem_utilizador
    return


if __name__ == "__main__":
    app.run()
